FROM python:3.10


WORKDIR /app

COPY  ./requirements.txt  /app/requirements.txt

#install pip and dependencies
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir -r /app/requirements.txt


#Copy all file to container
COPY . /app

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

